//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALL_LOGIN_INFO
    {
        public long USER_ID { get; set; }
        public string USER_LOGIN_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public short USER_STATUS { get; set; }
    }
}
