//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALL_ADDRESS
    {
        public ALL_ADDRESS()
        {
            this.CUSTOMERs = new HashSet<CUSTOMER>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
        }
    
        public int ADDRESS_ID { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public string DETAIL_ADDRESS { get; set; }
        public int ZIPCODE { get; set; }
    
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
    }
}
