//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALL_DEPARTMENT
    {
        public ALL_DEPARTMENT()
        {
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
        }
    
        public string DEPARTMENT_NAME { get; set; }
        public long DEPARTMENT_ID { get; set; }
        public string DEPARTMENT_ROOM { get; set; }
        public decimal DEPARTMENT_BUDGET { get; set; }
    
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
    }
}
