//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT_PHOTO_INFO
    {
        public long CONTRACT_PHOTO_ID { get; set; }
        public long CONTRACT_USER_ID { get; set; }
        public long CONTRACT_PHOTOREPAIRER_ID { get; set; }
        public System.DateTime CONTRACT_START_DATE { get; set; }
        public System.DateTime CONTRACT_END_DATE { get; set; }
        public decimal CONTRACT_PAYMENT { get; set; }
        public short CONTRACT_STATUS { get; set; }
    
        public virtual ALL_PHOTO ALL_PHOTO { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
