//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.CONTRACT_PHOTO_INFO = new HashSet<CONTRACT_PHOTO_INFO>();
            this.ORDER_EQUIPMENT_INFO = new HashSet<ORDER_EQUIPMENT_INFO>();
        }
    
        public long CUSTOMER_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public int CUSTOMER_ADDRESS_ID { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public short CUSTOMER_IS_ASSOCIATE { get; set; }
        public short CUSTOMER_SEX { get; set; }
    
        public virtual ALL_ADDRESS ALL_ADDRESS { get; set; }
        public virtual ICollection<CONTRACT_PHOTO_INFO> CONTRACT_PHOTO_INFO { get; set; }
        public virtual ICollection<ORDER_EQUIPMENT_INFO> ORDER_EQUIPMENT_INFO { get; set; }
    }
}
