//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.CONTRACT_EQUIPMENT_INFO = new HashSet<CONTRACT_EQUIPMENT_INFO>();
            this.CONTRACT_PHOTO_INFO = new HashSet<CONTRACT_PHOTO_INFO>();
            this.DISPATCHING_ORDER_INFO = new HashSet<DISPATCHING_ORDER_INFO>();
        }
    
        public long EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public short EMPLOYEE_SEX { get; set; }
        public int EMPLOYEE_ADDRESS_ID { get; set; }
        public string EMPLOYEE_EMAIL { get; set; }
        public System.DateTime EMPLOYEE_ENTRY_TIME { get; set; }
        public string EMPLOYEE_DEPART_NAME { get; set; }
        public int EMPLOYEE_SALARY { get; set; }
        public string EMPLOYEE_TITLE { get; set; }
    
        public virtual ALL_ADDRESS ALL_ADDRESS { get; set; }
        public virtual ALL_DEPARTMENT ALL_DEPARTMENT { get; set; }
        public virtual ICollection<CONTRACT_EQUIPMENT_INFO> CONTRACT_EQUIPMENT_INFO { get; set; }
        public virtual ICollection<CONTRACT_PHOTO_INFO> CONTRACT_PHOTO_INFO { get; set; }
        public virtual ICollection<DISPATCHING_ORDER_INFO> DISPATCHING_ORDER_INFO { get; set; }
    }
}
