//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT_INFO
    {
        public EQUIPMENT_INFO()
        {
            this.ORDER_EQUIPMENT_INFO = new HashSet<ORDER_EQUIPMENT_INFO>();
        }
    
        public long EQUIPMENT_ID { get; set; }
        public string EQUIPMENT_BRAND { get; set; }
        public short EQUIPMENT_IS_RENT { get; set; }
        public short EQUIPMENT_IS_USABLE { get; set; }
        public string EQUIPMENT_COLOR { get; set; }
        public string EQUIPMENT_CATEGORY { get; set; }
        public decimal EQUIPMENT_PRICE { get; set; }
        public decimal EQUIPMENT_RENT { get; set; }
        public long EQUIPMENT_WAREHOUSE { get; set; }
        public string EQUIPMENT_DETAIL { get; set; }
    
        public virtual WAREHOUSE_INFO WAREHOUSE_INFO { get; set; }
        public virtual ICollection<ORDER_EQUIPMENT_INFO> ORDER_EQUIPMENT_INFO { get; set; }
    }
}
