//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitieFinal : DbContext
    {
        public EntitieFinal()
            : base("name=EntitieFinal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AAA> AAAs { get; set; }
        public DbSet<ALL_ADDRESS> ALL_ADDRESS { get; set; }
        public DbSet<ALL_DEPARTMENT> ALL_DEPARTMENT { get; set; }
        public DbSet<ALL_LOGIN_INFO> ALL_LOGIN_INFO { get; set; }
        public DbSet<ALL_PHOTO> ALL_PHOTO { get; set; }
        public DbSet<ALL_USER_TEL> ALL_USER_TEL { get; set; }
        public DbSet<CONTRACT_EQUIPMENT_INFO> CONTRACT_EQUIPMENT_INFO { get; set; }
        public DbSet<CONTRACT_PHOTO_INFO> CONTRACT_PHOTO_INFO { get; set; }
        public DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public DbSet<DISPATCHING_ORDER_INFO> DISPATCHING_ORDER_INFO { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public DbSet<EQUIPMENT_INFO> EQUIPMENT_INFO { get; set; }
        public DbSet<ORDER_EQUIPMENT_INFO> ORDER_EQUIPMENT_INFO { get; set; }
        public DbSet<TESTTABLE> TESTTABLEs { get; set; }
        public DbSet<WAREHOUSE_INFO> WAREHOUSE_INFO { get; set; }
    }
}
