//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_EQUIPMENT_INFO
    {
        public ORDER_EQUIPMENT_INFO()
        {
            this.DISPATCHING_ORDER_INFO = new HashSet<DISPATCHING_ORDER_INFO>();
        }
    
        public long ORDER_ID { get; set; }
        public long ORDER_USER_ID { get; set; }
        public System.DateTime ORDER_START_DATE { get; set; }
        public decimal ORDER_PAYMENT { get; set; }
        public long ORDER_EQUIPMENT_ID { get; set; }
        public short ORDER_STATUS { get; set; }
        public System.DateTime ORDER_END_DATE { get; set; }
        public string ORDER_ADDRESS_DETAIL { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ICollection<DISPATCHING_ORDER_INFO> DISPATCHING_ORDER_INFO { get; set; }
        public virtual EQUIPMENT_INFO EQUIPMENT_INFO { get; set; }
    }
}
