//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE_INFO
    {
        public WAREHOUSE_INFO()
        {
            this.EQUIPMENT_INFO = new HashSet<EQUIPMENT_INFO>();
        }
    
        public long WAREHOUSE_ID { get; set; }
        public string WAREHOUSE_ADDRESS { get; set; }
        public long WAREHOUSE_CAPACITY { get; set; }
    
        public virtual ICollection<EQUIPMENT_INFO> EQUIPMENT_INFO { get; set; }
    }
}
